[alias]
rr = "run --release"

[build]
rustc-wrapper = "/usr/bin/sccache"

[expand]
pager = true

[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-args=-fuse-ld=/usr/bin/mold"]
