#! /bin/sh

# Hotkey daemon
pgrep -x sxhkd > /dev/null || sxhkd &

# Configure physical displays
LMONIT=HDMI-0
RMONIT=DP-2
xrandr --output $RMONIT --right-of $LMONIT
xrandr --output $RMONIT --primary
xrandr --output $LMONIT --mode 2560x1440 --rate 144
xrandr --output $RMONIT --mode 2560x1440 --rate 144

# Monitor setup
bspc monitor $RMONIT -d I II III IV V
bspc monitor $LMONIT -d VI VII VIII IX X
bspc monitor $LMONIT -s $RMONIT

# Gaps
bspc config border_width         0
bspc config window_gap          12

# Misc. bspwm
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Cursor
xsetroot -cursor_name left_ptr &

# Bars
$HOME/.config/polybar/launch.sh &

# Background
feh --bg-fill $HOME/Pictures/Wallpapers/current.jpg &

# Compositor
#picom -b --backend xr_glx_hybrid --vsync --glx-no-stencil --use-damage &

# Notifications
killall -q gsd-print-notifications
dunst &

# Keyring
gnome-keyring-daemon --start --components=pkcs11

# Polkit agent
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# Fixes for specific programs
bspc rule -a frame state=tiled
