#! /bin/sh

# Hotkey daemon
pgrep -x sxhkd > /dev/null || sxhkd &

# Monitor setup
bspc monitor -d I II III IV V VI VII VIII IX X

# Gaps
bspc config border_width         0
bspc config window_gap          12

# Misc. bspwm
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Cursor
xsetroot -cursor_name left_ptr &

# Bars
$HOME/.config/polybar/launch.sh &

# Background
feh --bg-fill $HOME/Pictures/Wallpapers/current.jpg &

# Compositor
picom -b &

# Notifications
killall -q gsd-print-notifications
dunst &

# Keyring
gnome-keyring-daemon --start --components=pkcs11

# Polkit agent
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
