[alias]
rr = "run --release"

[build]
rustc-wrapper = "/usr/bin/sccache"

[expand]
pager = true

[target.x86_64-unknown-linux-gnu]
# Use mold
linker = "clang"
rustflags = ["-C", "link-args=-fuse-ld=/usr/bin/mold"]

[profile.debug]
# Disable incremental compilation for sccache to do its thing
incremental = false

[profile.dev]
# Disable incremental compilation for sccache to do its thing
incremental = false
